#pragma once

#include <swa/swa.h>
#include <xkbcommon/xkbcommon.h>
#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

struct swa_xkb_context {
	struct xkb_context* context;
	struct xkb_keymap* keymap;
	struct xkb_state* state;

	struct xkb_compose_table* compose_table;
	struct xkb_compose_state* compose_state;
};

bool swa_xkb_init_default(struct swa_xkb_context*);
bool swa_xkb_init_compose(struct swa_xkb_context*);
void swa_xkb_finish(struct swa_xkb_context*);

// Returns all currently effectively active keyboard modifiers
enum swa_keyboard_mod swa_xkb_modifiers(struct swa_xkb_context*);
enum swa_keyboard_mod swa_xkb_modifiers_state(struct xkb_state*);

// Returns the null-terminated utf8 text input generated by this
// in *out_utf8 if there is any. Must be freed.
// Returns whether a compose sequence was canceled in *cancelled.
void swa_xkb_key(struct swa_xkb_context*, uint8_t keycode,
	char** out_utf8, bool* canceled);
const char* swa_xkb_key_name(struct swa_xkb_context*, enum swa_key);
const char* swa_xkb_key_name_keymap(struct xkb_keymap*, enum swa_key);
void swa_xkb_update_state(struct swa_xkb_context*, int mods[3],
	int layouts[3]);

#ifdef __cplusplus
}
#endif
